export enum Color {
  PRIMARY_BLACK = 'primaryBlack',
  SECONDARY_BLACK = 'secondaryBlack',
  TERTIARY_BLACK = 'tertiaryBlack',
  PRIMARY_BLUE = 'primaryBlue',
  SECONDARY_BLUE = 'secondaryBlue',
  PRIMARY_GREEN = 'primaryGreen',
  PRIMARY_GREY = 'primaryGrey',
  SECONDARY_GREY = 'secondaryGrey',
  TERTIARY_GREY = 'tertiaryGrey',
  PRIMARY_ORANGE = 'primaryOrange',
  SECONDARY_ORANGE = 'secondaryOrange',
  PRIMARY_PINK = 'primaryPink',
  SECONDARY_PINK = 'secondaryPink',
  TERTIARY_PINK = 'tertiaryPink',
  PRIMARY_PURPLE = 'primaryPurple',
  SECONDARY_PURPLE = 'secondaryPurple',
  PRIMARY_RED = 'primaryRed',
  PRIMARY_WHITE = 'primaryWhite',
  SECONDARY_WHITE = 'secondaryWhite',
  HOVER_STANDARD = 'hoverStandard',
  HOVER_ALTERNATIVE = 'hoverAlternative',
}

export enum Breakpoint {
  MOBILE_S = 'MOBILE_S',
  MOBILE_M = 'MOBILE_M',
  MOBILE_L = 'MOBILE_L',
  TABLET = 'TABLET',
  LAPTOP = 'LAPTOP',
  LAPTOP_M = 'LAPTOP_M',
  LAPTOP_L = 'LAPTOP_L',
  DESKTOP = 'DESKTOP',
}

export enum Variant {
  XS = 'xs',
  SMALL = 'small',
  NORMAL = 'normal',
  MEDIUM = 'medium',
  LARGE = 'large',
  XL = 'xl',
  XXL = 'xxl',
  XXXL = 'xxxl',
  HUGE = 'huge',
}

export const breakpointPx: Record<Breakpoint, number> = {
  [Breakpoint.MOBILE_S]: 320,
  [Breakpoint.MOBILE_M]: 375,
  [Breakpoint.MOBILE_L]: 425,
  [Breakpoint.TABLET]: 768,
  [Breakpoint.LAPTOP]: 1024,
  [Breakpoint.LAPTOP_M]: 1260,
  [Breakpoint.LAPTOP_L]: 1440,
  [Breakpoint.DESKTOP]: 2560,
}

export const Theme = {
  colors: {
    [Color.PRIMARY_BLACK]: 'var(--fg)',
    [Color.SECONDARY_BLACK]: 'var(--fg)',
    [Color.TERTIARY_BLACK]: 'var(--fg)',
    [Color.PRIMARY_BLUE]: 'var(--primary)',
    [Color.SECONDARY_BLUE]: 'var(--secondary)',
    [Color.PRIMARY_GREEN]: '#00FF00',
    [Color.PRIMARY_GREY]: 'var(--muted-foreground)',
    [Color.SECONDARY_GREY]: 'var(--muted-foreground)',
    [Color.TERTIARY_GREY]: 'var(--muted)',
    [Color.PRIMARY_ORANGE]: '#97240D',
    [Color.SECONDARY_ORANGE]: 'var(--accent)',
    [Color.PRIMARY_PINK]: 'var(--bg)',
    [Color.SECONDARY_PINK]: 'var(--muted)',
    [Color.TERTIARY_PINK]: 'var(--accent)',
    [Color.PRIMARY_PURPLE]: 'var(--secondary)',
    [Color.SECONDARY_PURPLE]: 'var(--secondary)',
    [Color.PRIMARY_RED]: '#FF0000',
    [Color.PRIMARY_WHITE]: 'var(--bg)',
    [Color.SECONDARY_WHITE]: 'var(--muted)',
    [Color.HOVER_STANDARD]: 'color-mix(in srgb, var(--fg) 10%, transparent)',
    [Color.HOVER_ALTERNATIVE]: 'color-mix(in srgb, var(--fg) 80%, transparent)',
  },
  fontFamily: 'Clash Display, Spline Sans, Poppins, sans-serif',
  fontSize: {
    [Variant.XS]: '14px',
    [Variant.SMALL]: '16px',
    [Variant.NORMAL]: '18px',
    [Variant.MEDIUM]: '20px',
    [Variant.LARGE]: '24px',
    [Variant.XL]: '28px',
    [Variant.XXL]: '40px',
    [Variant.XXXL]: '42px',
    [Variant.HUGE]: '72px',
  },
  fontWeight: {
    bold: 600,
    normal: 400,
  },
  lineHeight: {
    xs: 20 / 14,
    small: 24 / 16,
    normal: 28 / 20,
    medium: 32 / 24,
    large: 36 / 28,
    xl: 48 / 40,
  },
  letterSpacing: '0.6px',
}
